const ChatData = [
  {
    id: '1',
    user: '1',
    name: 'Rutvik',
    profileImage:'https://assets.ubsapp.com/profileImages/TsSe0U9XoC.jpeg',
    message: 'Hello Dhara !',
    react: [
      {id: '01', name: 'rutvik', reaction: 'heart'},
      {id: '02', name: 'dhara', reaction: 'smile'},
    ],
    time: '12:01',
  },
  {
    id: '2',
    user: '2',
    name: 'Dhara',
    profileImage:'https://assets.ubsapp.com/profileImages/R1UTOL6F71.jpeg',
    message: 'Hello Rutvik',
    react: [
      {id: '01', name: 'rutvik', reaction: 'happy'},
      {id: '02', name: 'dhara', reaction: 'heart'},
    ],
    time: '12:03',
  },
  {
    id: '3',
    user: '1',
    name: 'Rutvik',
    profileImage:'https://assets.ubsapp.com/profileImages/TsSe0U9XoC.jpeg',
    message: 'How are you Dhara ?',
    react: null,
    time: '12:03',
  },
  {
    id: '4',
    user: '2',
    name: 'Dhara',
    profileImage:'https://assets.ubsapp.com/profileImages/R1UTOL6F71.jpeg',
    message: 'I am fine thank you and what about you',
    react: null,
    time: '12:03',
  },
  {
    id: '5',
    user: '1',
    name: 'Rutvik',
    profileImage:'https://assets.ubsapp.com/profileImages/TsSe0U9XoC.jpeg',
    message: 'I am also fine',
    react: [{id: '01', name: 'rutvik', reaction: 'happy'}],
    time: '12:04',
  },
  {
    id: '6',
    user: '1',
    name: 'Rutvik',
    profileImage:'https://assets.ubsapp.com/profileImages/TsSe0U9XoC.jpeg',
    message: 'What you are doing ?',
    react: [
      {id: '01', name: 'rutvik', reaction: 'smile'},
      {id: '02', name: 'dhara', reaction: 'happy'},
    ],
    time: '12:05',
  },
  {
    id: '7',
    user: '2',
    name: 'Dhara',
    profileImage:'https://assets.ubsapp.com/profileImages/R1UTOL6F71.jpeg',
    message: 'Great Question ! I am just do chat with you ',
    react: [{id: '02', name: 'dhara', reaction: 'heart'}],
    time: '12:05',
  },
  {
    id: '8',
    user: '1',
    name: 'Rutvik',
    profileImage:'https://assets.ubsapp.com/profileImages/TsSe0U9XoC.jpeg',
    message: 'Hello Dhara !',
    react: null,
    time: '12:05',
  },
  {
    id: '8',
    user: '2',
    name: 'Dhara',
    profileImage:'https://assets.ubsapp.com/profileImages/R1UTOL6F71.jpeg',
    message: 'Hello Rutvik',
    react: null,
    time: '12:06',
  },
  {
    id: '10',
    user: '1',
    name: 'Rutvik',
    profileImage:'https://assets.ubsapp.com/profileImages/TsSe0U9XoC.jpeg',
    message: 'How are you Dhara ?',
    react: [
      {id: '01', name: 'rutvik', reaction: 'heart'},
      {id: '02', name: 'dhara', reaction: 'happy'},
    ],
    time: '12:06',
  },
  {
    id: '11',
    user: '2',
    name: 'Dhara',
    profileImage:'https://assets.ubsapp.com/profileImages/R1UTOL6F71.jpeg',
    message: 'I am fine thank you and what about you',
    react: null,
    time: '12:07',
  },
  {
    id: '12',
    user: '1',
    name: 'Rutvik',
    profileImage:'https://assets.ubsapp.com/profileImages/TsSe0U9XoC.jpeg',
    message: 'I am also fine',
    react: [{id: '02', name: 'dhara', reaction: 'smile'}],
    time: '12:07',
  },
  {
    id: '13',
    user: '1',
    name: 'Rutvik',
    profileImage:'https://assets.ubsapp.com/profileImages/TsSe0U9XoC.jpeg',
    message: 'https://www.npmjs.com/package/react-native-animatable',
    react: [
      {id: '01', name: 'rutvik', reaction: 'smile'},
      {id: '02', name: 'dhara', reaction: 'heart'},
    ],
    time: '12:10',
  },
  {
    id: '14',
    user: '2',
    name: 'Dhara',
    profileImage:'https://assets.ubsapp.com/profileImages/R1UTOL6F71.jpeg',
    message: 'Great Question ! I am just do chat with you ',
    react: null,
    time: '12:10',
  },
];

export {ChatData};
